### ISSUE TITLE
THE SYSTEM SHOULD DISPLAY THE EMPLOYEE LIST

### ISSUE THREAD

**Issue by acmiras** [vasavah/vci-kanaka_auntie-annes-testing-phase#10]
![image](https://user-images.githubusercontent.com/60170851/73230266-99994200-41b7-11ea-9b9d-af4c6a0a9d4f.png)

**Comment by acmiras** [comment]
May we request a search botton or can you make it in alphabetical order. Thanks

**Comment by acmiras** [comment]
![image](https://user-images.githubusercontent.com/60170851/73230389-00b6f680-41b8-11ea-8666-50e9ca6738b1.png)

when we click the time record botton

**Comment by acmiras** [comment]
![image](https://user-images.githubusercontent.com/60170851/73230418-2a701d80-41b8-11ea-99d8-707907e41b12.png)


puwede po palagyan ng employee name para hindi po kami malito and to make sure na nasa Tamang Time record profile po kami.

**Comment by fersieval0216** [comment]
confirm and validate by ms.aileen
