### ISSUE TITLE
HOLIDAY MANAGEMENT

### ISSUE THREAD

**Issue by acmiras** [vasavah/vci-kanaka_auntie-annes-testing-phase#11]
![image](https://user-images.githubusercontent.com/60170851/73232137-42966b80-41bd-11ea-82db-026991d3c198.png)

**Comment by acmiras** [comment]
DOBLE DOBLE PO YUNG MGA STORES PO. 

TAPOS REQUEST PO NAMIN NA I-SUNOD SUNOD YUNG NUMBER PABABA PARA MALAMAN DIN PO NAMIN KUNG LAHAT NG STORE NAMIN AY NASA LIST PO. 

PARANG MADAMI PO KASING WALA EH.

**Comment by fersieval0216** [comment]
confirm and validate by ms.aileen miras
