### ISSUE TITLE
HR REPORTS - DTR

### ISSUE THREAD

**Issue by acmiras** [vasavah/vci-kanaka_auntie-annes-testing-phase#12]
SYSTEM DISPLAYED THE SELECTED DEPARTMENT FOR PRINTING

![image](https://user-images.githubusercontent.com/60170851/73233182-b7b77000-41c0-11ea-943e-13f92edfb2f0.png)

**Comment by acmiras** [comment]
![image](https://user-images.githubusercontent.com/60170851/73233237-e03f6a00-41c0-11ea-8b3e-aae5712da011.png)

**Comment by acmiras** [comment]
![image](https://user-images.githubusercontent.com/60170851/73233286-fcdba200-41c0-11ea-9ec3-8f7527f3451f.png)

**Comment by acmiras** [comment]
![image](https://user-images.githubusercontent.com/60170851/73233334-21377e80-41c1-11ea-844c-82ec74add20f.png)

**Comment by acmiras** [comment]
MULTIPLE NAMES PO YUNG LUMABAS TAPOS INCOMPLETE PO YUNG NAMES NA NAGENERATE FOR HR DEPARTMENT HND PO LAHAT NAKUHA NA UNDER HR DEPARTMENT PO.

**Comment by fersieval0216** [comment]
confirm and validate by ms.aileen
