### ISSUE TITLE
ADD EMPLOYEE - NO EMPLOYEE NUMBER

### ISSUE THREAD

**Issue by acmiras** [vasavah/vci-kanaka_auntie-annes-testing-phase#13]
![image](https://user-images.githubusercontent.com/60170851/73233632-0b768900-41c2-11ea-934f-7b0284f394ac.png)

**Comment by acmiras** [comment]
WALA PO SYANG EMPLOYEE NUMBER, TEAM, ANG POSITION

**Comment by acmiras** [comment]
![image](https://user-images.githubusercontent.com/60170851/73233707-4d073400-41c2-11ea-931f-d5c190706b94.png)

 NAG TRY PO KAMI MAG ADD NG 5 EMPLOYEES SA (HR - EMPLOYEE- ADD EMPLOYEE)

**Comment by acmiras** [comment]
PUWEDE PO BANG PALAGYAN NG EMPLOYEE NUMBER/ TEAM / POSITION DUN SA ADD EMPLOYEE BOTTON???

**Comment by acmiras** [comment]
IMPORTANTE PO KASI YUNG EMPLOYEE NUMBER PARA SA QUICK PUNCH.. THANK YOU PO

**Comment by fersieval0216** [comment]
confirm and validated by ms.aileen miras
