### ISSUE TITLE
CANNOT PUNCH IN ON THE OTHER DAY

### ISSUE THREAD

**Issue by acmiras** [vasavah/vci-kanaka_auntie-annes-testing-phase#14]
MAY EMPLOYEE PO KAMI NA UMABOT NG MADALING ARAW YUNG PUNCH OUT NIA. 

BALE NUNG MAG PPUNCH IN NA PO SYA NA SUSUNOD NA ARAW HND NA PO SYA MAKAPAG PUNCH IN.

**Comment by acmiras** [comment]
![image](https://user-images.githubusercontent.com/60170851/74299544-f552f600-4d87-11ea-9b7a-25dfeb182f81.png)

**Comment by fersieval0216** [comment]
as discussed, quick punch is problem here po

**Comment by acmiras** [comment]
PAG NAKALIMOT MAG PUNCH OUT DAPAT BLANK YUNG PUNCH OUT PERO DAPAT MAKAPAG PUNCH IN PA DIN SYA KINABUKASAN.

**Comment by fersieval0216** [comment]
Confirm and validated by ms.aileen
