### ISSUE TITLE
CANNOT LOG IN IN CLOUD AND KIOSK

### ISSUE THREAD

**Issue by acmiras** [vasavah/vci-kanaka_auntie-annes-testing-phase#15]
![image](https://user-images.githubusercontent.com/60170851/73626815-432f7600-4685-11ea-8867-ba0160a13784.png)
![image](https://user-images.githubusercontent.com/60170851/73626835-55111900-4685-11ea-97a5-e1bda2b96563.png)

**Comment by fersieval0216** [comment]
This issue has been resolved
