### ISSUE TITLE
CLOUD PROBLEM IN LOGGING IN

### ISSUE THREAD

**Issue by acmiras** [vasavah/vci-kanaka_auntie-annes-testing-phase#16]
![image](https://user-images.githubusercontent.com/60170851/73904052-ca732880-48d5-11ea-94d2-8cbec7b822d1.png)

**Comment by fersieval0216** [comment]
Hi Ms. Aileen, try typing po your organization name (pretiolas) in the search box it should redirect na po sa kanaka cloud link ninyo po, please comment me back if okay na po thanks! :)

**Comment by acmiras** [comment]
Sir ayaw po talga

**Comment by fersieval0216** [comment]
confirmed and validated by ms.aileen miras
