### ISSUE TITLE
KIOSK NOT WORKING IN INCOGNITO

### ISSUE THREAD

**Issue by acmiras** [vasavah/vci-kanaka_auntie-annes-testing-phase#17]
![image](https://user-images.githubusercontent.com/60170851/73904851-600fb780-48d8-11ea-931f-97744ba2c874.png)

**Comment by fersieval0216** [comment]
Hi Ma'am Aileen, kahit po hindi sa incognito hindi po na gana? sa lahat po ba ng pc or sa pc ninyo lang po?

**Comment by fersieval0216** [comment]
confirmed and validated by ms.aileen miras
