### ISSUE TITLE
WALA PONG PROMPT SA EMAIL REGARDING SA CHANGE PASSWORD 

### ISSUE THREAD

**Issue by acmiras** [vasavah/vci-kanaka_auntie-annes-testing-phase#18]
![image](https://user-images.githubusercontent.com/60170851/74137780-5f09bd80-4c2b-11ea-9475-25cd56c94848.png)

![image](https://user-images.githubusercontent.com/60170851/74137823-73e65100-4c2b-11ea-8cfc-f35cc9a906cb.png)

![image](https://user-images.githubusercontent.com/60170851/74137838-7f397c80-4c2b-11ea-9bb7-a419303dd1ee.png)

**Comment by acmiras** [comment]
pag ni click ko po yung submit lumalabas naman po yung "success" pero sa email wala namn po sa messages ng new password.

**Comment by fersieval0216** [comment]
confirm and validated by ms. aileen miras
