### ISSUE TITLE
CANNOT LOG IN

### ISSUE THREAD

**Issue by acmiras** [vasavah/vci-kanaka_auntie-annes-testing-phase#19]
![image](https://user-images.githubusercontent.com/60170851/74714562-baf4c780-5265-11ea-9d55-4e0fe1921d79.png)

**Comment by acmiras** [comment]
Lagi po syang ganyan. kaya tinatamad na po mag log in yung mga EMPLOYEES namin. nag lload lang sya ng ganyan. may internet naman po kami.

**Comment by fersieval0216** [comment]
Confirm and validated by Ms. Aileen Miras
