### ISSUE TITLE
PROBLEM IN LOGGING IN 

### ISSUE THREAD

**Issue by acmiras** [vasavah/vci-kanaka_auntie-annes-testing-phase#2]
Hindi po kami makapag log in sa ibang PC. Pero gumagana naman po yung Quick Punch
yung Log In lang po ang hnd gumagana kahit tama naman po yung username at password.
pero pag mali po yung username at password lumalabas naman po yung "oppsss"

**Comment by acmiras** [comment]
browser: Google Chrome latest version
operating system: windows 7 pro 64bit
device: desktop pc hardware: intel pentium procee, ram 6 gb, board asus 3rdgen
error: not existing"but when you click the login button in login menu, it will not redirect to the 
profile of the employee the pop up succesful is not showing. but when password input is wrong. the error occur. "the popup error"

**Comment by fersieval0216** [comment]
Sa Kanaka Kiosk po ba to?

**Comment by acmiras** [comment]
opo Sir. may Extra Pc po kasi kami dito, yun po yung ginamit namin para mag Log In mga employees namin sa malapit sa entrance.

**Comment by fersieval0216** [comment]
pero sa ibang pc po gumagana ng maayos yung Kanaka Kiosk tama po ba? dyan lang po sa extra pc ninyo nag ka error?

**Comment by acmiras** [comment]
opo sir dito sa PC namin ni mam reneerose nakakapag Log in kaming dalawa po.

**Comment by acmiras** [comment]
![image](https://user-images.githubusercontent.com/60170851/72883238-ece63d00-3d3e-11ea-8442-d4b13de9a748.png)

**Comment by acmiras** [comment]
![image](https://user-images.githubusercontent.com/60170851/72883386-2cad2480-3d3f-11ea-9d03-6c1907436253.png)

**Comment by acmiras** [comment]
![image](https://user-images.githubusercontent.com/60170851/72883492-5a926900-3d3f-11ea-9dea-ea0ceb9ef0e7.png)

**Comment by acmiras** [comment]
sir kahapon nag OT ako ng 3 HOURS pero ang lumalabas sa system 2 HOURS lang yung nababasa nia.

**Comment by fersieval0216** [comment]
Hi Ma'am Aileen, pagawan po ng bagong ticket ma'am, isang bug report po isang ticket, thanks po

**Comment by fersieval0216** [comment]
duplicate ticket
