### ISSUE TITLE
CANNOT PUNCH THE BREAK 

### ISSUE THREAD

**Issue by acmiras** [vasavah/vci-kanaka_auntie-annes-testing-phase#20]
![image](https://user-images.githubusercontent.com/60170851/74714956-8f261180-5266-11ea-809b-19cc386a810a.png)

**Comment by acmiras** [comment]
nag punch naman po yung employee namin pero hnd po sya maka pag punch ng break. 

hnd po na cclick yung botton ng break out at break in.

**Comment by fersieval0216** [comment]
confirm and validated by ms. aileen miras
