### ISSUE TITLE
GENERATED TAR

### ISSUE THREAD

**Issue by acmiras** [vasavah/vci-kanaka_auntie-annes-testing-phase#21]
![image](https://user-images.githubusercontent.com/60170851/74717756-e7134700-526b-11ea-97f8-8c1cee8ea222.png)

FIX 13 DAYS PO KAMI PERO NAKALAGAY PO 12 DAYS LANG PO.

TAPOS GAGAMIT PO AKO NG OFFSET SA UNDERTIME AT LATE PANU PO KAYA YUN?

PILING KO MALI DIN PO COMPUTE NG LATE AT UNDERTIME NA NAKUHA NIA.

**Comment by acmiras** [comment]
![image](https://user-images.githubusercontent.com/60170851/74717931-38bbd180-526c-11ea-9270-665c93d29da0.png)

 NAG FILE NA DIN PO AKO NG OT PERO HND PA DIN PO NAG REREFLECT. INAAPROVE KO DIN PO YUN PERO HND PA DIN NAG REREFLECT

**Comment by acmiras** [comment]
![image](https://user-images.githubusercontent.com/60170851/74718051-702a7e00-526c-11ea-8b93-bbadb898cd45.png)


PATI PO LEAVE NG FILE DIN AKO PERO HND DIN NAG REFLECT.

**Comment by acmiras** [comment]
![image](https://user-images.githubusercontent.com/60170851/74718134-951ef100-526c-11ea-85e8-622cd05d1ed7.png)

AYAN PO YUNG PROOF.

**Comment by acmiras** [comment]
![image](https://user-images.githubusercontent.com/60170851/74718234-c0a1db80-526c-11ea-89cf-a9313186652f.png)

**Comment by acmiras** [comment]
![image](https://user-images.githubusercontent.com/60170851/75944337-604ca400-5ed2-11ea-871b-8eed4b91fd0a.png)

**Comment by acmiras** [comment]
ni lapat po namin yung system sa timecard namin nag punch alteration po kami para magawa yung punch ng timecard namin para macheck kung parehas lalabas yung summary namin sa sysrem


![image](https://user-images.githubusercontent.com/60170851/75944555-fd0f4180-5ed2-11ea-88e1-8480e50a1ab3.png)

**Comment by acmiras** [comment]
![image](https://user-images.githubusercontent.com/60170851/75944658-3e075600-5ed3-11ea-92f5-fb0608c36df0.png)

pero hnd po ganyan lumabas sa system.

**Comment by acmiras** [comment]
ETO PO YUNG PINAKA MAHALAGA SAMIN YUNG MAGEGENERATE NA TAR NG SYSTEM.

PLS PAKI AYOS PO ITO SALAMAT PO.

**Comment by VCI-Jojo** [comment]
@acmiras We've uploaded the patch for the fixed 13 days, please validate on your end. Thank you.
