### ISSUE TITLE
REQUESTING FOR SEARCH BOTTON AT ALPHABETICAL ORDER

### ISSUE THREAD

**Issue by acmiras** [vasavah/vci-kanaka_auntie-annes-testing-phase#23]
![image](https://user-images.githubusercontent.com/60170851/74720030-0f9d4000-5270-11ea-9503-497a121ccc44.png)

**Comment by acmiras** [comment]
EMPLOYEE SCHEDULE PLS SANA MAY SEARCH BOTTON AT ALPHABETICAL ORDER

**Comment by acmiras** [comment]
![image](https://user-images.githubusercontent.com/60170851/74720192-568b3580-5270-11ea-9304-0bc9e7af1d29.png)

**Comment by acmiras** [comment]
LEAVE CREDIT NAKA ALPHABETICAL NAMAN PO PLS SEARCH BOTTON N LANG PO SANA. THANKS PO.

**Comment by acmiras** [comment]
![image](https://user-images.githubusercontent.com/60170851/74720281-7fabc600-5270-11ea-8419-de4f5e433f66.png)

**Comment by fersieval0216** [comment]
confirm and validated by ms.aileen miras
