### ISSUE TITLE
SITE MANAGEMENT

### ISSUE THREAD

**Issue by acmiras** [vasavah/vci-kanaka_auntie-annes-testing-phase#24]
![image](https://user-images.githubusercontent.com/60170851/74720616-05c80c80-5271-11ea-88c2-d675699e46b2.png)

**Comment by acmiras** [comment]
SIR PA NUMERICAL ORDER NA LANG PO AND SEARCH BOTTON N LANG PO ULIT. THANKS PO.

**Comment by fersieval0216** [comment]
confirm and validated by ms. aileen miras
