### ISSUE TITLE
DISCREPANCY IN SCHED IN CLOUD AND KIOSK

### ISSUE THREAD

**Issue by acmiras** [vasavah/vci-kanaka_auntie-annes-testing-phase#26]
![image](https://user-images.githubusercontent.com/60170851/74811895-6b79ce80-532d-11ea-8ab2-2cdb31d58c19.png)

![image](https://user-images.githubusercontent.com/60170851/74811921-77659080-532d-11ea-80a7-ce37d1ab0a34.png)

**Comment by acmiras** [comment]
![image](https://user-images.githubusercontent.com/60170851/75020527-e548be00-54cd-11ea-99af-6903006d6134.png)

DISCREPANCY PO SA DATE NG KIOSK PO.

**Comment by fersieval0216** [comment]
confirm and validated by ms. aileen miras
