### ISSUE TITLE
CANNOT PUNCH IN KIOSK

### ISSUE THREAD

**Issue by acmiras** [vasavah/vci-kanaka_auntie-annes-testing-phase#28]
![image](https://user-images.githubusercontent.com/60170851/75124585-3255ab80-56eb-11ea-8cd1-ce08366e1a9e.png)

**Comment by acmiras** [comment]
may internet naman po kami. both  dito sa pc ko at sa baba. pero umiikot lang sya

**Comment by fersieval0216** [comment]
Confirm and validated by Ms. Aileen Miras
