### ISSUE TITLE
HOLIDAY DISCREPANCY

### ISSUE THREAD

**Issue by acmiras** [vasavah/vci-kanaka_auntie-annes-testing-phase#29]
![image](https://user-images.githubusercontent.com/60170851/75136918-1ff66480-5721-11ea-88ea-96e0a9e6193f.png)

**Comment by acmiras** [comment]
![image](https://user-images.githubusercontent.com/60170851/75314223-17756980-589a-11ea-931c-8e5ce94319e0.png)

HOLIDAY PO KAHAPON HND PO KAMI PUMASOK PERO NAKA TAG SYA AS ABSENT

**Comment by fersieval0216** [comment]
> 
> 
> ![image](https://user-images.githubusercontent.com/60170851/75314223-17756980-589a-11ea-931c-8e5ce94319e0.png)
> 
> HOLIDAY PO KAHAPON HND PO KAMI PUMASOK PERO NAKA TAG SYA AS ABSENT

Hi Ma'am Aileen Good afternoon po, hindi po kayo absent nyan nakalagay lang po na absent because you have a schedule for that day pero may "/ holiday" naman po so it means isasama pa din po yang araw na yan sa payroll bayad pa din po yan.

**Comment by acmiras** [comment]
COPY PO THANK YOU PO :)

**Comment by fersieval0216** [comment]
pa change ko nalang po yung color to green ma'am para hindi po nakaka alarm tignan :)

**Comment by fersieval0216** [comment]
> 
> 
> COPY PO THANK YOU PO :)

Welcome po :)

**Comment by fersieval0216** [comment]
Close and Validated by Ms.Aileen Miras
