### ISSUE TITLE
DISCREPANCY IN OVERTIME

### ISSUE THREAD

**Issue by acmiras** [vasavah/vci-kanaka_auntie-annes-testing-phase#3]
![image](https://user-images.githubusercontent.com/60170851/72955910-d096de80-3dd8-11ea-9b9a-76ef7a28754f.png)

* sched po namin 9 - 6 
nag OT po kami ng 3 hours

nakalagay po dian sa overtime hrs: 2.77

![image](https://user-images.githubusercontent.com/60170851/72955927-e60c0880-3dd8-11ea-8dab-306ea3619788.png)

* dito naman po sa apply overtime 
2 hours na po yung max nung arrow down.
hindi lumalabas yung 3 HOURS.

dapat po may 1, 1.5, 2, 2.5, & 3 HOURS yung arroW Down.

![image](https://user-images.githubusercontent.com/60170851/72955962-fc19c900-3dd8-11ea-803d-2ea65352f461.png)

* Pag ni check yung OVERTIME NAMIN SA cloud 1 hour lang yung nababasa nia.

**Comment by acmiras** [comment]
![image](https://user-images.githubusercontent.com/60170851/74713215-11acd200-5263-11ea-95db-37a41b5257bf.png)

**Comment by acmiras** [comment]
![image](https://user-images.githubusercontent.com/60170851/74713239-2c7f4680-5263-11ea-8bd8-808c5ac59b3e.png)


2.76 pa din yung nakalagay po.

**Comment by acmiras** [comment]
still not working.

**Comment by acmiras** [comment]
![image](https://user-images.githubusercontent.com/60170851/75943315-a2c0b180-5ecf-11ea-86fa-2ccf5454cb59.png)

![image](https://user-images.githubusercontent.com/60170851/75943381-c5eb6100-5ecf-11ea-9318-fbc4d43d48bb.png)


YUNG NABABASA NA OT 1.5 HOURS OT LANG PO.

**Comment by acmiras** [comment]
![image](https://user-images.githubusercontent.com/60170851/75943541-38f4d780-5ed0-11ea-80b5-b892d3837b84.png)

dito po 3 hours OT KO pero 2.5 lang yung nababasa nia

**Comment by fersieval0216** [comment]
Confirm and validated by ms.aileen miras
