### ISSUE TITLE
LEAVE / VL W/ PAY DID NOT SHOW IN TAR SUMMARY

### ISSUE THREAD

**Issue by acmiras** [vasavah/vci-kanaka_auntie-annes-testing-phase#30]
![image](https://user-images.githubusercontent.com/60170851/75420058-20396e80-5972-11ea-8a5d-f6fb85b2db10.png)

![image](https://user-images.githubusercontent.com/60170851/75420130-43641e00-5972-11ea-9b9c-5c947ddcbf7f.png)

![image](https://user-images.githubusercontent.com/60170851/75420185-6989be00-5972-11ea-8aaf-23898b6fd0e4.png)

**Comment by acmiras** [comment]
![image](https://user-images.githubusercontent.com/60170851/75965383-bab22880-5f03-11ea-9fb2-d422d4a59335.png)

**Comment by acmiras** [comment]
WALA PO SYANG USED..  BLANK PO SYA

**Comment by VCI-Jojo** [comment]
@acmiras We've applied fixes for the leaves on the TAR, kindly validate on your end. Thank you.
