### ISSUE TITLE
ISSUE IN KIOSK AND CLOUD

### ISSUE THREAD

**Issue by acmiras** [vasavah/vci-kanaka_auntie-annes-testing-phase#31]
![image](https://user-images.githubusercontent.com/60170851/75939451-32149780-5ec5-11ea-9e85-73157f47acb1.png)

YUNG NI CHECK KO SA LOG IN SA KIOSK

![image](https://user-images.githubusercontent.com/60170851/75939547-72741580-5ec5-11ea-8e16-9bb90fd55fc3.png)

![image](https://user-images.githubusercontent.com/60170851/75939588-8c155d00-5ec5-11ea-9fc1-f9e70eeb61aa.png)

![image](https://user-images.githubusercontent.com/60170851/75939606-9df70000-5ec5-11ea-8b97-4a2fa7428db1.png)

AYAN PO SIR,

**Comment by fersieval0216** [comment]
Confirm and validated by ms. aileen
