### ISSUE TITLE
question 1 

### ISSUE THREAD

**Issue by acmiras** [vasavah/vci-kanaka_auntie-annes-testing-phase#33]
![image](https://user-images.githubusercontent.com/60170851/86213556-77638000-bbac-11ea-9ac0-95b589e4a2a6.png)

para saan po yung "register"
hnd naman po ako HO EXECUTIVE

tapos yung schedule po nakalagay
DEPARTMENT MANAGER PO.

**Comment by VCI-Jojo** [comment]
@acmiras we can change this in the system, this was encoded on the datasheets provided, also these are template names for the schedule and register.
