### ISSUE TITLE
loading

### ISSUE THREAD

**Issue by acmiras** [vasavah/vci-kanaka_auntie-annes-testing-phase#34]
![image](https://user-images.githubusercontent.com/60170851/86214220-754df100-bbad-11ea-9589-8da664ecc56e.png)

Ganyang lang po sya loading pero hnd wala naman lumalabas na data

**Comment by acmiras** [comment]
![image](https://user-images.githubusercontent.com/60170851/86214390-b2b27e80-bbad-11ea-862f-10144128c1cf.png)


kahit sa kiosk ganyan lang din lumalabas

may internet naman po ako

**Comment by acmiras** [comment]
![image](https://user-images.githubusercontent.com/60170851/86439271-d7882c80-bd3a-11ea-9e1a-7425406ef3dd.png)

still loading the CLOUD

NGAUN WHITE NA LANG PO SYA

**Comment by VCI-Jojo** [comment]
@acmiras are you still experiencing this concern?

**Comment by VCI-Jojo** [comment]
Resolved, for closing @zetaleona
