### ISSUE TITLE
missing VL OPS 

### ISSUE THREAD

**Issue by acmiras** [vasavah/vci-kanaka_auntie-annes-testing-phase#35]
![image](https://user-images.githubusercontent.com/60170851/86215434-2903b080-bbaf-11ea-86d3-b91c829d61b0.png)

wala po yung VL - OPS po

**Comment by VCI-Jojo** [comment]
@zetaleona for datasheet validation and upload if needed.

**Comment by zetaleona** [comment]
> @zetaleona for datasheet validation and upload if needed.

This is noted.

**Comment by VCI-Jojo** [comment]
@acmiras Please validate this on your end if it is already showing. Thank you
