### ISSUE TITLE
Try logging thru phone

### ISSUE THREAD

**Issue by acmiras** [vasavah/vci-kanaka_auntie-annes-testing-phase#36]
![Screenshot_20200707_140454](https://user-images.githubusercontent.com/60170851/86725228-5224a680-bfde-11ea-9cf2-5994c6a41cd1.jpg)

Ganyan po pag click ko ng link hnd sya violet 

![Screenshot_20200707_140815](https://user-images.githubusercontent.com/60170851/86725323-6668a380-bfde-11ea-8da2-295da129fc1d.jpg)

Loading lang din po

**Comment by acmiras** [comment]
![received_1131881823865521](https://user-images.githubusercontent.com/60170851/86728811-a715ec00-bfe1-11ea-8b0b-41163f96529e.jpeg)

Naka access po kami sa kiosk via phone sa log in tapos ganyan po itsura nia 

Wala syang punch sa taas 

Kasi yung quick punch po hnd gumagana nag lloading lang sa phone

**Comment by VCI-Jojo** [comment]
@acmiras please use the link provided below to access the Kiosk:

https://kiosk.kodanda.cloud/#/login/pretiolas

Let me know if you can do Quick Punch and Login already. Thanks

**Comment by VCI-Jojo** [comment]
Duplicate ticket of #50, for closing @zetaleona
