### ISSUE TITLE
quick punch via desk top

### ISSUE THREAD

**Issue by acmiras** [vasavah/vci-kanaka_auntie-annes-testing-phase#38]
![image](https://user-images.githubusercontent.com/60170851/86993483-aeeab180-c1d6-11ea-8da6-f4001996bd1b.png)

im trying to quick punch (kiosk) via my desktop pero hnd po nag susuccess yung entry kaya dun na lang ako sa log in sa kiosk ng punch

**Comment by acmiras** [comment]
hnd po sya nag susubmit pag ni cclick ko po

**Comment by VCI-Jojo** [comment]
Resolved as per @acmiras, for closing.

**Comment by VCI-Jojo** [comment]
Duplicate ticket of #50, for closing @zetaleona
