### ISSUE TITLE
SOBRANG DAMING BREAK OUT AT BREAK IN SA BOTTON SA LOG IN

### ISSUE THREAD

**Issue by acmiras** [vasavah/vci-kanaka_auntie-annes-testing-phase#39]
![image](https://user-images.githubusercontent.com/60170851/87002245-c2544780-c1eb-11ea-8f64-bdc41fe35aed.png)

![image](https://user-images.githubusercontent.com/60170851/87002328-ee6fc880-c1eb-11ea-9b49-ca583df899b5.png)

KAHIT SA CHANGE SCHEDULE NA TAB ANG DAMING BREAK NA KALAGAY

**Comment by zetaleona** [comment]
Hi!

Kindly check the punch buttons. Thank you!

**Comment by VCI-Jojo** [comment]
Resolved for closing.

**Comment by zetaleona** [comment]
This issue is resolved.
