### ISSUE TITLE
LATE PUNCH IN NOT TAGGED AS LATE

### ISSUE THREAD

**Issue by acmiras** [vasavah/vci-kanaka_auntie-annes-testing-phase#4]
![image](https://user-images.githubusercontent.com/60170851/73147400-2e396c80-40f2-11ea-8f11-c5a1d80ff42c.png)

**Comment by acmiras** [comment]
SYSTEM DOES NOT SAVED THE "PUNCH IN"IN TIME RECORDS AND NOT  TAGGED AS LATE

**Comment by acmiras** [comment]
![image](https://user-images.githubusercontent.com/60170851/74719324-c3053500-526e-11ea-8834-a87d4eb017f9.png)

**Comment by acmiras** [comment]
hnd po nag rereflect ng tama yung late at yung OT po.

**Comment by fersieval0216** [comment]
confirm and validated by ms.aileen miras
