### ISSUE TITLE
HOLIDAY CONCERN

### ISSUE THREAD

**Issue by acmiras** [vasavah/vci-kanaka_auntie-annes-testing-phase#42]
![image](https://user-images.githubusercontent.com/60170851/87640410-458c1500-c779-11ea-9e3b-15ce9d7c7430.png)

BAKIT SA SITES PO WALANG INDICATION OR SELECTION KUNG SINO YUNG PASOK SA HOLIDAY NA I ADD KO PO.

**Comment by acmiras** [comment]
![image](https://user-images.githubusercontent.com/60170851/87640668-a582bb80-c779-11ea-95b2-88431ffa6cd5.png)

AYAN NAKA NATIONAL TULOY PO NAKALAGAY IMBIS NA FOR BAGUIO HOLIDAY LANG PO SYA

**Comment by acmiras** [comment]
![image](https://user-images.githubusercontent.com/60170851/87752707-93fdea00-c833-11ea-9173-ccbdf97a7980.png)


SO AYAN NA PO NALAGAY DIAN SA GILID YUNG HOLLIDAY FOR BAGUIO LANG PO KASI SYA.

**Comment by VCI-Jojo** [comment]
@acmiras you will need to add Baguio under Site Management first so you can assign the specific holiday to Baguio. Thanks

**Comment by acmiras** [comment]
![image](https://user-images.githubusercontent.com/60170851/87908269-b04e9080-ca98-11ea-912d-7718948c594e.png)



SIR KAHIT GUSTO KO PO MAG ADD NG SITE KASO WALA PONG NA CCLICK PO SA PAG ADD NG HOLIDAY PO

**Comment by acmiras** [comment]
![image](https://user-images.githubusercontent.com/60170851/87908380-dbd17b00-ca98-11ea-990b-ef422df1a559.png)


KAHIT I EDIT KO PO YUNG HOLIDAY NG BAGUIO WALA PA DIN BOTTON DUN SA SITE NA PART PO.

**Comment by VCI-Jojo** [comment]
Please check datasheets for sites e.g. Baguio, Davao @zetaleona

**Comment by zetaleona** [comment]
May I have the copy of datasheets sir., @Vasavah Projects
<projects@vasavah.com>

**Comment by VCI-Jojo** [comment]
@acmiras as agreed during the meeting, kindly add sites and local holidays via the system, closing this ticket.
