### ISSUE TITLE
TIMESHEET OR TAR

### ISSUE THREAD

**Issue by acmiras** [vasavah/vci-kanaka_auntie-annes-testing-phase#44]
![image](https://user-images.githubusercontent.com/60170851/87643548-969e0800-c77d-11ea-91e0-a0b440587b19.png)

WALANG BOTTON PO KUNG SAAN MA GEGENERATE YUNG TAR / TIMESHEET PO.

**Comment by VCI-Jojo** [comment]
@acmiras DTR and TAR generation buttons are under Register.

Click on Register > VIEW> Then check which register you want to access, click VIEW> Check if there are pending Approvals, then click LOCK > Click on Generate Daily Time Records > Click Finalize > Click Time and Attendance Reports > Click Finalize.

**Comment by acmiras** [comment]
![image](https://user-images.githubusercontent.com/60170851/87754928-90209680-c838-11ea-9397-4d7ca54f20ab.png)


SIR SAAN PO YUNG LOCK?

**Comment by VCI-Jojo** [comment]
@acmiras as relayed via SMS, you should be able to see the registers and cutoffs, kindly validate on your end.

**Comment by VCI-Jojo** [comment]
Resolved as per @acmiras as per run through the system.
