### ISSUE TITLE
REQUESTING TEMPORARY APPROVER OF THE SAMPLE STORE WHO USES THE KONDANDA

### ISSUE THREAD

**Issue by acmiras** [vasavah/vci-kanaka_auntie-annes-testing-phase#47]
![image](https://user-images.githubusercontent.com/60170851/87760755-d2e76c00-c842-11ea-8705-2088c6f15988.png)

HI PO REQUEST LANG PO AKO NA AKO MUNA PANSAMANTALA MAG APPROVE PO SAUNIMART AT SA GREENBELT PO NA STORE NA GUMAGAMIT NG SYSTEM PO THANKS PO.

**Comment by acmiras** [comment]
![image](https://user-images.githubusercontent.com/60170851/87896409-bafa2d00-ca7a-11ea-8690-58a273b1d522.png)


salamat po.

pero ang nakita ko lang sa approver po ay PRETZEL SPECIALIST 

SA CHANGE SCHEDULE PART PO YUNG KAY ALFRED FRIAS NAG FILE PO SYA PERO HND LUMALABAS SAKIN PO..

**Comment by acmiras** [comment]
![image](https://user-images.githubusercontent.com/60170851/87896532-12000200-ca7b-11ea-83e5-926fe1fe57ed.png)

**Comment by VCI-Jojo** [comment]
Resolved as per @acmiras as she can approve applications already.
