### ISSUE TITLE
FORGET PASSWORD CONCERN

### ISSUE THREAD

**Issue by acmiras** [vasavah/vci-kanaka_auntie-annes-testing-phase#48]
.
![image](https://user-images.githubusercontent.com/60170851/88631481-ce457200-d0e4-11ea-96ef-c28093f4bebc.png)

nakalagay po success pero wala naman po dumadating sa email na verification

**Comment by VCI-Jojo** [comment]
This will be activated after sign off of Pilot Run.

**Comment by VCI-Jojo** [comment]
@acmiras we've activated this already so you can test, kindly check it is already working on your end.
