### ISSUE TITLE
TIMESHEET / REGISTER CONCERN 

### ISSUE THREAD

**Issue by acmiras** [vasavah/vci-kanaka_auntie-annes-testing-phase#49]
![image](https://user-images.githubusercontent.com/60170851/88632779-a6efa480-d0e6-11ea-8594-9769156c150f.png)

**Comment by acmiras** [comment]
DALAWA LANG KAMI NI ALFRED FRIAS AT AKO ANG NAG PUNCH PERO NUNG NAG GENERATE AKO ANG ANDAMING EMPLOYEE NUMBER TAPOS YUNG EMPLOYEE NUMBER KO WALA PO

**Comment by acmiras** [comment]
DI B PO DAPAT PUWEDENG SORTING YAN LIKE PUWEDE PER DEPARTMENT

**Comment by acmiras** [comment]
NAKA LINE UP LANG SYANG GANYAN WALA KASING PANGALAN SO HND KO ALAM KUNG SINO SINO YAN

**Comment by acmiras** [comment]
SANA MAY SEARCH BOTTON PO AT SORT BOTTON PARA PAG MERON KAILANGAN MADALING HANAPIN THANKS

**Comment by acmiras** [comment]
![image](https://user-images.githubusercontent.com/60170851/88634459-f7680180-d0e8-11ea-9175-670b15e63d2e.png)

**Comment by acmiras** [comment]
YUNG SORTONG PLS KUNG PUWEDE PO BY DEPARTMENT

**Comment by acmiras** [comment]
![image](https://user-images.githubusercontent.com/60170851/88636082-0bacfe00-d0eb-11ea-9052-064fe311587b.png)


ETO PO YUNG KANAKA

**Comment by acmiras** [comment]
![image](https://user-images.githubusercontent.com/60170851/88636375-647c9680-d0eb-11ea-9a99-8a706c2de37a.png)

**Comment by acmiras** [comment]
PLEASE SEE THIS TICKETS

**Comment by acmiras** [comment]
![image](https://user-images.githubusercontent.com/60170851/89522617-16b30d00-d814-11ea-9152-06dedfac5b31.png)

**Comment by acmiras** [comment]
still cant generated the timesheet

**Comment by acmiras** [comment]
![image](https://user-images.githubusercontent.com/60170851/89522992-b6709b00-d814-11ea-903d-0c034e9c765b.png)

**Comment by acmiras** [comment]
ganyan po lumalabas sa HO pag ni click yung display na botton

**Comment by acmiras** [comment]
![image](https://user-images.githubusercontent.com/60170851/89523152-fc2d6380-d814-11ea-9219-1d1c48a26b42.png)

wala ba syang search botton hnd po ba talaga sya naka per department?

**Comment by acmiras** [comment]
sa mga names na yan wala name ko at ni ALFRED FRIAS

**Comment by VCI-Jojo** [comment]
Check for Rose Macavinta.

Filtering via Department, Surnames for easier searching.
