### ISSUE TITLE
EARLY OUT

### ISSUE THREAD

**Issue by acmiras** [vasavah/vci-kanaka_auntie-annes-testing-phase#5]
![image](https://user-images.githubusercontent.com/60170851/73148020-1ca59400-40f5-11ea-9c7f-07be28b58229.png)

SYSTEM DOES NOT PROMPTED A MESSAGE "YOU WANT THIS TO APPLY AS EARLY OUT?"

**Comment by acmiras** [comment]
SYSTEM DOES NOT REDIRECT THE USER TO THE EARLY OUT APPLICATION FORM

**Comment by acmiras** [comment]
![image](https://user-images.githubusercontent.com/60170851/76284815-38e24680-62d9-11ea-8d4e-72c549bda410.png)

**Comment by fersieval0216** [comment]
Confirm and validated by ms.aileen miras
