### ISSUE TITLE
PROBLEM IN LOGGING IN POS AND ANDROID PHONE

### ISSUE THREAD

**Issue by acmiras** [vasavah/vci-kanaka_auntie-annes-testing-phase#50]
![image](https://user-images.githubusercontent.com/60170851/88637030-3b103a80-d0ec-11ea-90fb-876348a0d852.png)

**Comment by VCI-Jojo** [comment]
@acmiras Incorrect URL for the Kiosk, it should be:

https://kiosk.kodanda.cloud/#/login/pretiolas

**Comment by VCI-Jojo** [comment]
Resolved as per @acmiras

**Comment by VCI-Jojo** [comment]
Inconsistent Access - please observe.
