### ISSUE TITLE
HOLIDAY SITE NUMBERING

### ISSUE THREAD

**Issue by acmiras** [vasavah/vci-kanaka_auntie-annes-testing-phase#52]
![image](https://user-images.githubusercontent.com/60170851/89862486-ab35ba80-dbda-11ea-86fa-0fe846aeca2a.png)

**Comment by acmiras** [comment]
SIR PA ALLIGN NAMAN NG SITE NA NUMBERING PABABA PA TOP TO BOTTOM YUNG NUMBERING TAPOS YUNG NUMBERING NA MAG UUMPISA SA MABABA PA TAAS

**Comment by VCI-Jojo** [comment]
@acmiras We've applied the changes you've requested, kindly validate on your end. Thank you.
