### ISSUE TITLE
HOLIDAY CONCERN

### ISSUE THREAD

**Issue by acmiras** [vasavah/vci-kanaka_auntie-annes-testing-phase#53]
![image](https://user-images.githubusercontent.com/60170851/91030844-58c0b900-e632-11ea-8ba4-020cf9ac86ee.png)

**Comment by acmiras** [comment]
HND PO BA PUWEDE ISUNOD SUNOD YUNG MGA HOLIDAY NA NAKADEPEND SA DATE KASI HALOHALO SYA NAKAKAHILO PO TIGNAN SALAMAT PO PARANG JAN - DEC YUNG FORMAT

**Comment by VCI-Jojo** [comment]
@acmiras We've applied the changes you've requested, kindly validate on your end. Thank you.
