### ISSUE TITLE
NO PUNCH ALTERRATION

### ISSUE THREAD

**Issue by acmiras** [vasavah/vci-kanaka_auntie-annes-testing-phase#55]
![image](https://user-images.githubusercontent.com/60170851/92203648-3d687000-eeb4-11ea-900b-c6ceacbc1db1.png)

**Comment by VCI-Jojo** [comment]
@acmiras Upon checking, there is no Punch Out for August 28 so please have the employee Punch Out so the Punch Alteration button will appear. Thank you.

**Comment by acmiras** [comment]
![image](https://user-images.githubusercontent.com/60170851/93155816-808ad480-f739-11ea-897b-3c76e1fd27bf.png)

**Comment by acmiras** [comment]
sir panu po yung ganyan yung sept 14 nakalimutan ko mag punch hnd ko na po b mag ppunch alteration po yun? PAG NO PUNCH OUT NO PAY NA PO SYA?

**Comment by VCI-Jojo** [comment]
@acmiras We've deployed a patch for this, please validate on your end if it is already working. Thank you,
