### ISSUE TITLE
MISSING PUNCH BOTTONS IN LOG IN

### ISSUE THREAD

**Issue by acmiras** [vasavah/vci-kanaka_auntie-annes-testing-phase#56]
![image](https://user-images.githubusercontent.com/60170851/92204372-f0859900-eeb5-11ea-953b-cbf27aaa4f71.png)

**Comment by acmiras** [comment]
TAPOS AUG 31 PA PO YUNG DATE SIR PUNCH RECORD PO

**Comment by VCI-Jojo** [comment]
@acmiras We've applied a patch for the missing buttons yesterday, kindly validate if you can see them already. Thank you.
