### ISSUE TITLE
ISSUE IN OPERATION CUT OFF

### ISSUE THREAD

**Issue by acmiras** [vasavah/vci-kanaka_auntie-annes-testing-phase#57]
![image](https://user-images.githubusercontent.com/60170851/92207974-cc798600-eebc-11ea-9cb5-c4674d6460fc.png)

**Comment by acmiras** [comment]
![image](https://user-images.githubusercontent.com/60170851/92208032-e5823700-eebc-11ea-801c-e2ee35d9bd90.png)

BAKIT MERON STORE MANAGER SA CUT OFF NG OPERATION PO. 

PRETZEL SPECIALIST AT TEAM LEADER PO ANG SA CUT OFF NA TO

**Comment by acmiras** [comment]
![image](https://user-images.githubusercontent.com/60170851/92211180-9b9c4f80-eec2-11ea-983d-c20bb65c1e12.png)

**Comment by acmiras** [comment]
![image](https://user-images.githubusercontent.com/60170851/92211332-e0c08180-eec2-11ea-9b34-291cc82045be.png)

 MALI YUNG PAYROLL PERIOD NA NAKALAGAY
JUNE 01 - 30, 2020

**Comment by VCI-Jojo** [comment]
@acmiras We've applied the patch to address your concern for this, please validate on your end. Thank you.
