### ISSUE TITLE
DTR ISSUE

### ISSUE THREAD

**Issue by acmiras** [vasavah/vci-kanaka_auntie-annes-testing-phase#58]
![image](https://user-images.githubusercontent.com/60170851/92208264-6b05e700-eebd-11ea-95e3-7909960ebe31.png)

**Comment by acmiras** [comment]
WALA PONG NAME AT STORE CODE... IMPORTANTE PO YUN EH

**Comment by acmiras** [comment]
![image](https://user-images.githubusercontent.com/60170851/92208395-ac969200-eebd-11ea-90f1-9c2465b2913c.png)


ASAN PO YUNG WORKING HOURS NIA? ANG MERON LANG PO NUM,BER N NAKALAGAY SA LATE PO.

**Comment by acmiras** [comment]
![image](https://user-images.githubusercontent.com/60170851/92208475-db146d00-eebd-11ea-9ac1-64c204d1fce3.png)

**Comment by acmiras** [comment]
![image](https://user-images.githubusercontent.com/60170851/92208505-ecf61000-eebd-11ea-9829-d9f93edf34fc.png)

**Comment by acmiras** [comment]
![image](https://user-images.githubusercontent.com/60170851/92208559-08611b00-eebe-11ea-8b0d-2bfdc5108eca.png)



ETO NA PO PINAKA LAST SA DTR 

LAHAT PO NAKA ZERO.

**Comment by VCI-Jojo** [comment]
@acmiras We are working on the store code / site and will advise once it has been added for your checking. Thank you.
