### ISSUE TITLE
Time and Attendance Report issue

### ISSUE THREAD

**Issue by acmiras** [vasavah/vci-kanaka_auntie-annes-testing-phase#59]
![image](https://user-images.githubusercontent.com/60170851/92210824-06995680-eec2-11ea-9421-4f315dd78633.png)

anu po ibigsabihin nian naka thousand yung hours

**Comment by acmiras** [comment]
![image](https://user-images.githubusercontent.com/60170851/92210946-3ea09980-eec2-11ea-8ba8-ff725af24c1f.png)


eto po ganun din PERO WALANG EMPLOYEE NAME AND POSITION PO..

**Comment by acmiras** [comment]
PALAGYAN NAMAN PO NG STORE CODE PO.

**Comment by acmiras** [comment]
ETO GAWA KO  PO TO MANUAL 
SAME CUT OFF AUG 28 - SEPT 12
KAY ALMONTE

![image](https://user-images.githubusercontent.com/60170851/92212008-ec607800-eec3-11ea-99eb-1adf8fade54b.png)


88 HOURS EQUIVALENT TO 11 DAYS OK NAKUHA NIO NMN PO YUN  PERO SAINYO PO WALANG SYANG HOLIDAY PAY. 


TAPOS TIMESHEET KO PO MERON STORE CODE SOBRANG IMPORTANTE PO NUN.

**Comment by VCI-Jojo** [comment]
@acmiras We've applied the patch to address your concern for this, please validate on your end. Thank you.
