### ISSUE TITLE
USER WILL CHECK THE TOTAL HOURS

### ISSUE THREAD

**Issue by acmiras** [vasavah/vci-kanaka_auntie-annes-testing-phase#6]
![image](https://user-images.githubusercontent.com/60170851/73148797-0b5e8680-40f9-11ea-8536-6abc85d50eb8.png)

**Comment by acmiras** [comment]
![image](https://user-images.githubusercontent.com/60170851/73148895-81fb8400-40f9-11ea-8969-98b5359634a6.png)

DISCREPANCY IN TOTAL WORKING HOURS

**Comment by acmiras** [comment]
THE SYSTEM DOES NOT COMPUTE THE CORRECT TOTAL WORK HOURS WHEN GENERATED IN THE   "TAR"

**Comment by VCI-Jojo** [comment]
@acmiras We've uploaded fixes for the Total Work Hours, please validate on your end. Thank you.
