### ISSUE TITLE
QUICK PUNCH NOT WORKING ALWAYS

### ISSUE THREAD

**Issue by acmiras** [vasavah/vci-kanaka_auntie-annes-testing-phase#60]
![image](https://user-images.githubusercontent.com/60170851/93032635-3cc69b00-f665-11ea-9751-68998d97e177.png)

**Comment by acmiras** [comment]
LAGI PO SYANG GANYAN HND NA DIN PO GUMAGANA SA STORE YUNG QUICK PUNCH KAYA SA LOG IN SILA NAG PPUNCH
TAPOS PAG PINAPASOK YUNG PIN SABI MALI DAW YUNG PIN OR EMPLOYEE NUMBER KAHIT TAMA NAMAN PO YUNG NILALAGAY PO.

**Comment by VCI-Jojo** [comment]
@acmiras We've deployed a patch for this, please validate on your end if it is already working. Thank you,
