### ISSUE TITLE
OT CONCERN

### ISSUE THREAD

**Issue by acmiras** [vasavah/vci-kanaka_auntie-annes-testing-phase#61]
![image](https://user-images.githubusercontent.com/60170851/93033169-ab0c5d00-f667-11ea-9072-7264a39050f2.png)

**Comment by acmiras** [comment]
HND KO PO ALAM BAKIT MAY OT NA 0.50 PERO YUNG UNDERTIME PO B NA O.50 IBIGSABIHIN PO B NUN 30 MINS? HND NMAN 50 MINS PO SYA?

**Comment by VCI-Jojo** [comment]
@acmiras Yes, 0.5 means 30 mins, using this conversion: 30 mins / 60 mins = 0.5
