### ISSUE TITLE
OVERBREAK CONCERN

### ISSUE THREAD

**Issue by acmiras** [vasavah/vci-kanaka_auntie-annes-testing-phase#62]
![image](https://user-images.githubusercontent.com/60170851/93033373-8cf32c80-f668-11ea-8de5-42f9972ef111.png)

**Comment by acmiras** [comment]
NALAGAY PO SA OVERBREAK O.17 DAPAT PO 1O MINS PO DI B ?

**Comment by VCI-Jojo** [comment]
@acmiras 0.17 is equivalent to 10 mins, 10 mins / 60 mins = 0.17
