### ISSUE TITLE
REGISTER CONCERN

### ISSUE THREAD

**Issue by acmiras** [vasavah/vci-kanaka_auntie-annes-testing-phase#63]
![image](https://user-images.githubusercontent.com/60170851/93034140-a3e74e00-f66b-11ea-87ab-871a6afd2296.png)
 NASA OPERATION CUT OFF PO AKO SIR PERO MERON PA DIN NAKIKITANG MGA STORE HEADS NA NAMES NA KAILANGAN GENERATE 

SA OPERATION CUT OFF SIR PRETZEL SPECIALIST AT TEAM LEADER PO ANG NI PAPAYROLL PO NAMIN DUN

**Comment by acmiras** [comment]
![image](https://user-images.githubusercontent.com/60170851/93034233-fcb6e680-f66b-11ea-97bb-56a64fd13925.png)


AYAN PO MERON PO MGA NAMES NG STORE HEADS OR MANAGERS  PO

**Comment by VCI-Jojo** [comment]
@acmiras Hi Aileen, this was based on the datasheets submitted before, to change an employees register, please go his/her profile and then edit the register on the profile. Please see screenshot below for reference:

![Change Register](https://user-images.githubusercontent.com/64577963/93158991-df534c80-f73f-11ea-8ffe-7bca4e7c4910.png)

**Comment by acmiras** [comment]
![image](https://user-images.githubusercontent.com/60170851/94370196-1a328880-0121-11eb-849f-7435f8c08e4b.png)



BAKIT WALA PO YUNG SPET 6 TO 20 NA CUTOFF PO.

**Comment by acmiras** [comment]
![image](https://user-images.githubusercontent.com/60170851/95010368-6454c600-065b-11eb-8ec8-f1e2cd28068e.png)


![image](https://user-images.githubusercontent.com/60170851/95010400-aa118e80-065b-11eb-8795-cfe34068fd53.png)



LATEST CUT OFF NG OPS PERO ANDUN PA DIN YUNG MGA STORE MANAGERS NA NI EDIT KO NA YUNG REGISTER NILA PARA MAPUNTA SILA SA HEAD OFFICE REGISTER

**Comment by acmiras** [comment]
![image](https://user-images.githubusercontent.com/60170851/95162705-cdae1380-07d8-11eb-9f53-51c6286d0a9e.png)


loading lang po.
