### ISSUE TITLE
loading issue again

### ISSUE THREAD

**Issue by acmiras** [vasavah/vci-kanaka_auntie-annes-testing-phase#65]
![image](https://user-images.githubusercontent.com/60170851/94364434-ba75b680-00fb-11eb-9f54-b8447697264f.png)

**Comment by acmiras** [comment]
hnd po ako maka out ngaun po

**Comment by acmiras** [comment]
![image](https://user-images.githubusercontent.com/60170851/94364455-e4c77400-00fb-11eb-8b1e-fd08986061e8.png)

**Comment by acmiras** [comment]
even sa cloud ganyan din po sya

**Comment by VCI-Jojo** [comment]
@acmiras Patch has been uploaded for the loading time records, please check if you are still encountering the concern. Thank you.
