### ISSUE TITLE
employee concern

### ISSUE THREAD

**Issue by acmiras** [vasavah/vci-kanaka_auntie-annes-testing-phase#66]
![image](https://user-images.githubusercontent.com/60170851/94365698-8bfcd900-0105-11eb-877a-189797ab801d.png)

**Comment by acmiras** [comment]
![image](https://user-images.githubusercontent.com/60170851/94365743-e1d18100-0105-11eb-977e-51674f5d725d.png)


EM001163
AND 
EM001164 NO NAME

**Comment by acmiras** [comment]
![image](https://user-images.githubusercontent.com/60170851/94369246-30d5e100-011b-11eb-8ec9-7cb0a812c796.png)



PAG DATING PO SA PAGE 30 ONWARDS DOUBLE DOUBLE NA PO YUNG EMPLOYEE NUMBER.
YUNG ISANG NUMBER MAY NAME NG EMPLOYEE YUNG ISA WALA PO.

**Comment by VCI-Jojo** [comment]
@acmiras Duplicate Employee Number has been addressed, please confirm on your end. Thank you.
