### ISSUE TITLE
OT CONCERN

### ISSUE THREAD

**Issue by acmiras** [vasavah/vci-kanaka_auntie-annes-testing-phase#67]
![image](https://user-images.githubusercontent.com/60170851/94387427-b2119000-017c-11eb-80df-ac541a7c715e.png)

Total (hrs): 5.00

Punch: 9:00 AM - 2:00 PM

Overtime (hrs): 4.00 BAKIT MAY " APPLY OVERTIME " PO ?

**Comment by VCI-Jojo** [comment]
@acmiras Patch has been uploaded for this concern, please validate on your end. Thank you.

**Comment by acmiras** [comment]
![image](https://user-images.githubusercontent.com/60170851/94408428-5c061200-01a7-11eb-8015-7d09e1bd3a39.png)



sir anyare bakit double double na yung date po????

**Comment by VCI-Jojo** [comment]
@acmiras As per my SMS, please do clear cache on your browser and reopen, please let me know if there are no more duplicate dates. Thank you.
