### ISSUE TITLE
leave issue

### ISSUE THREAD

**Issue by acmiras** [vasavah/vci-kanaka_auntie-annes-testing-phase#69]
![image](https://user-images.githubusercontent.com/60170851/95008932-7715cd80-0650-11eb-854c-6e09387293eb.png)

bakit po yung type of leave ay "VL - OPS"?

taga VL - HO po ako eh

**Comment by VCI-Jojo** [comment]
@acmiras You will just need to assign VL - HO to your account and and remove VL - OPS. Thank you.

**Comment by acmiras** [comment]
panu po sir ?

**Comment by VCI-Jojo** [comment]
![Add Leave](https://user-images.githubusercontent.com/64577963/95035025-438d7e80-06f6-11eb-8413-2e131ec4fc27.PNG)

**Comment by acmiras** [comment]
![image](https://user-images.githubusercontent.com/60170851/95155255-5079a300-07c6-11eb-9b2f-493455170819.png)


SIR PANU PONG ASSIGN?
