### ISSUE TITLE
STATUS IN THE TIME RECORDS

### ISSUE THREAD

**Issue by acmiras** [vasavah/vci-kanaka_auntie-annes-testing-phase#7]
![image](https://user-images.githubusercontent.com/60170851/73149556-c4729000-40fc-11ea-819a-974c5da1e4f2.png)

**Comment by acmiras** [comment]
SYSTEM DOES NOT DISPLAY THE USER STATUS, PRESENT

**Comment by fersieval0216** [comment]
confirm and validate by ms. aileen miras

**Comment by fersieval0216** [comment]
confirm and validate by ms. aileen miras
