### ISSUE TITLE
LOADING ISSUE AGAIN

### ISSUE THREAD

**Issue by acmiras** [vasavah/vci-kanaka_auntie-annes-testing-phase#74]
![image](https://user-images.githubusercontent.com/60170851/95029823-a45c8d00-06dd-11eb-898c-71235a50a7be.png)

![image](https://user-images.githubusercontent.com/60170851/95029826-a9214100-06dd-11eb-8be2-1b2962eb8293.png)

**Comment by VCI-Jojo** [comment]
I've advised our support team regarding the reported concern, will update you once patch has been done. Thank you.
