### ISSUE TITLE
DISCREPANCY IN TAR AND DTR

### ISSUE THREAD

**Issue by acmiras** [vasavah/vci-kanaka_auntie-annes-testing-phase#75]
![image](https://user-images.githubusercontent.com/60170851/95156991-73a65180-07ca-11eb-8787-7b3a18a6c335.png)

TAR PO ITO

![image](https://user-images.githubusercontent.com/60170851/95157054-96d10100-07ca-11eb-9fac-a69fdc155516.png)

DTR PO ITO

**Comment by acmiras** [comment]
![image](https://user-images.githubusercontent.com/60170851/95157709-7013ca00-07cc-11eb-9136-9ce408e6c241.png)

**Comment by acmiras** [comment]
![image](https://user-images.githubusercontent.com/60170851/95157751-86218a80-07cc-11eb-8166-cab24cfcbc85.png)

**Comment by acmiras** [comment]
sir naguguluhan na po talaga ako sa TS na to.

HND KO PO MAGETS YUNG LATE NA "2"
YUNG ABSENT NA "1"
AT UNDERTIME NA "11"

**Comment by acmiras** [comment]
HND PO PUWEDE YUNG LATE AT UNDERTIME NAKA SUMMARY NA "PER MINUTE"

YUNG OT PO "NAKA PER HOUR"

**Comment by VCI-Jojo** [comment]
@acmiras I've already endorsed the DTR and TAR hours discrepancy to the team. However, the per hour is standard so we won't be converting it to minutes. Thanks

**Comment by VCI-Jojo** [comment]
HND KO PO MAGETS YUNG LATE NA "2"
YUNG ABSENT NA "1"
AT UNDERTIME NA "11"

@acmiras this is the number of times you've been late, absent and have undertime on your time records

**Comment by acmiras** [comment]
bale sir asan po yung summary ng late at undertime po?

**Comment by acmiras** [comment]
@acmiras this is the number of times you've been late, absent and have undertime on your time records

pero sir parang male pa din yung number of time na Undertime po hnd naman 11 times po yung UT po.

**Comment by acmiras** [comment]
sir kamusta po itong ticket na ito?

**Comment by VCI-Jojo** [comment]
Closing this ticket as validated via G Meets for validation of the DTR with TAR.
