### ISSUE TITLE
FRIAS TRANFER TO HO REGISTER

### ISSUE THREAD

**Issue by acmiras** [vasavah/vci-kanaka_auntie-annes-testing-phase#77]
![image](https://user-images.githubusercontent.com/60170851/95694782-6542b480-0c66-11eb-9a7a-05871305515e.png)

![image](https://user-images.githubusercontent.com/60170851/95694809-7986b180-0c66-11eb-8e50-55af41358937.png)

SI FRIAS PO WALA PA DIN SYA SA HEAD OFFICE NA REGISTER

**Comment by VCI-Jojo** [comment]
Closing this ticket as validated via G Meets for validation that Frias has appeared under HO Register
