### ISSUE TITLE
USER WILL CHECK THE LIST OF APPLY EARLY OUT

### ISSUE THREAD

**Issue by acmiras** [vasavah/vci-kanaka_auntie-annes-testing-phase#8]
![image](https://user-images.githubusercontent.com/60170851/73149805-f7695380-40fd-11ea-8020-4a6a32cb4e2d.png)

**Comment by acmiras** [comment]
SYSTEM DOES NOT DISPLAY THE LIST OF APPLIED EARLY OUT APPLICATION

**Comment by acmiras** [comment]
![image](https://user-images.githubusercontent.com/60170851/76392879-67c9ec80-63ad-11ea-85c6-4441e93ed703.png)

**Comment by fersieval0216** [comment]
![asdasdasd](https://user-images.githubusercontent.com/51081296/76393084-c98a5680-63ad-11ea-8978-b377296b0010.PNG)

**Comment by fersieval0216** [comment]
Confirm and validated by ms.aileen miras
