### ISSUE TITLE
leave concern

### ISSUE THREAD

**Issue by acmiras** [vasavah/vci-kanaka_auntie-annes-testing-phase#80]
![image](https://user-images.githubusercontent.com/60170851/96075469-aa245080-0edd-11eb-9d15-da4d0bb07503.png)

pag ni save po sya zero pa din po lumalabas

![image](https://user-images.githubusercontent.com/60170851/96075498-be684d80-0edd-11eb-9aab-9990793cfc2b.png)

**Comment by acmiras** [comment]
![image](https://user-images.githubusercontent.com/60170851/96075672-261e9880-0ede-11eb-9965-446ff02f3770.png)


![image](https://user-images.githubusercontent.com/60170851/96075700-33d41e00-0ede-11eb-9a4b-4f706f48b41f.png)

**Comment by VCI-Jojo** [comment]
Validated via G Meets, leave credits are saving properly.
