### ISSUE TITLE
CONCERN

### ISSUE THREAD

**Issue by acmiras** [vasavah/vci-kanaka_auntie-annes-testing-phase#81]
![image](https://user-images.githubusercontent.com/60170851/96077356-2751c480-0ee2-11eb-82f0-2bf727dd215a.png)

Schedule: 9:00 AM - 6:00 PM

Punch: 6:58 AM - 3:01 PM

October 12, 2020

Overbreak (hrs): 0.00
Undertime: 2.98
Overtime (hrs): 0.00
Total (hrs): 8.03
Status: Present

dapat sir undertime di b dapat: 3 to 6 pm and that is  3 HOURS
tapos yung duty 9 to 3 pm AND THAT IS 6 HOURS

**Comment by VCI-Jojo** [comment]
Closing for validation with DTR and TAR for this cutoff
