### ISSUE TITLE
LEAVE RECORDS

### ISSUE THREAD

**Issue by acmiras** [vasavah/vci-kanaka_auntie-annes-testing-phase#9]
![image](https://user-images.githubusercontent.com/60170851/73164295-a45ac500-412c-11ea-8771-7f4aa27d7235.png)

**Comment by acmiras** [comment]
WE DONT KNOW HOW THE SYSTEM CAN DETECT A HALF DAY LEAVE. THERE IS NO BOTTON FOR THE LEAVE THAT WANT TO USED. IF WHOLE DAY OR JUST A HALF DAY.

**Comment by acmiras** [comment]
AND ALSO THE LEAVE BALANCE IS INCORRECT. IT SHOULD BE 10.

**Comment by acmiras** [comment]
AND ALSO HOW THE SYSTEM WILL DETECT IF THE EMPLOYEE HAS A 
*WITHOUT LEAVE CREDITS"

**Comment by fersieval0216** [comment]
> 
> 
> AND ALSO HOW THE SYSTEM WILL DETECT IF THE EMPLOYEE HAS A
> *WITHOUT LEAVE CREDITS"

Hi ma'am aileen, hindi na po lalabas yung leave na yun kung wala na siyang credit for that leave. in short hindi niya na po ma apply yun. for example wala na siyang credit for VL, hindi na po lalabas sa selection yung VL sa apply leave

**Comment by acmiras** [comment]
![image](https://user-images.githubusercontent.com/60170851/74815394-1c836780-5334-11ea-855d-e619460d4348.png)

NI TRY PO NAMIN UBUSIN YUNG LEAVE NA 9 DAYS PERO NAG - 2 YUNG BALANCE NIA

**Comment by acmiras** [comment]
![image](https://user-images.githubusercontent.com/60170851/74815717-b6e3ab00-5334-11ea-9da3-8385c6326e1e.png)
 HND KO ALAM KUNG SAAN NG GALING YUNG 7 DAYS NA LEAVE BALANCE PO DIAN KASI SABI SA UNA 9 DAYS YUNG LEAVE BALANCE NIA TAPOS DIAN 7 DAYS KAYA NAG - 2 YUNG LEAVE BALANCE NIA DAHIL SA 7 DAYS

**Comment by fersieval0216** [comment]
Close and Validated by Ms.Aileen
